// Generate Cloudflare `_redirects` rules from content.
//
// This replaces a hand-written public/_redirects that hard-coded one event's
// slug in four rules. Every destination was that event's page, and those pages
// exist only while the event is `approved` -- so rejecting it would have
// removed the destination, failed verify-build.mjs check 7, and frozen the
// site on its last good deployment. Deriving the rules from the same content
// the pages are built from makes that impossible: an event that is not
// published contributes no rules.
//
// Everything below the header is derived from `events[].legacy_slugs`. The
// reasoning in the emitted header is transcribed from the file this replaces,
// because it was measured against the live asset router and is not
// recoverable by reading documentation.

const PREFIX = '/evenements/';

/**
 * Every URL spelling of one legacy slug that can reach the origin.
 *
 * Both the percent-encoded and the raw form, because Cloudflare's docs do not
 * say whether matching happens on the encoded or the decoded path and both
 * forms arrive from real browsers. Trailing-slash variants too, since Astro
 * builds directories and either form resolves.
 *
 * A Set because a pure-ASCII legacy slug encodes to itself, and emitting the
 * same source twice would be a duplicate rule rather than extra coverage.
 */
export function sourceUrls(slug) {
  const raw = PREFIX + slug;
  const enc = PREFIX + encodeURIComponent(slug);
  return [...new Set([enc, enc + '/', raw, raw + '/'])];
}

/**
 * Validate before generating. Each of these produces a rule that is worse than
 * no rule, so they throw rather than warn.
 */
export function checkLegacySlugs(events) {
  const live = new Map(events.map((e) => [e.slug, e]));
  const claimed = new Map();
  const problems = [];

  for (const e of events) {
    for (const legacy of e.legacy_slugs ?? []) {
      if (typeof legacy !== 'string' || legacy.trim() === '') {
        problems.push(`${e.slug}: a blank legacy slug would redirect ${PREFIX} itself`);
        continue;
      }
      // Shadowing a live page. Two different faults with one shape:
      // pointing at itself is a redirect loop dressed as a rule, and pointing
      // at another published event takes that event's URL away from it.
      if (live.get(legacy) === e) {
        problems.push(`${e.slug}: lists its own current slug as a legacy slug`);
      } else if (live.has(legacy)) {
        problems.push(
          `${e.slug}: legacy slug "${legacy}" is the current slug of ${live.get(legacy).slug}`,
        );
      }
      const owner = claimed.get(legacy);
      if (owner && owner !== e.slug) {
        problems.push(`legacy slug "${legacy}" is claimed by both ${owner} and ${e.slug}`);
      }
      claimed.set(legacy, e.slug);
    }
  }
  return problems;
}

/**
 * The file. Returns null when there is nothing to redirect, so the caller can
 * remove a stale file rather than write an empty one that looks configured.
 */
export function renderRedirects(events) {
  const problems = checkLegacySlugs(events);
  if (problems.length) {
    throw new Error(
      'legacy_slugs would generate broken redirects:\n  ' + problems.join('\n  '),
    );
  }

  const rules = [];
  for (const e of [...events].sort((a, b) => a.slug.localeCompare(b.slug))) {
    for (const legacy of [...(e.legacy_slugs ?? [])].sort()) {
      // The destination carries the trailing slash. Without it the asset
      // router adds a SECOND redirect to reach the real path, so the old URL
      // cost two hops.
      const dest = `${PREFIX}${e.slug}/`;
      for (const src of sourceUrls(legacy)) rules.push([src, dest]);
    }
  }
  if (!rules.length) return null;

  const width = Math.max(...rules.map(([s]) => s.length));
  const body = rules.map(([s, d]) => `${s.padEnd(width)}  ${d}  301`).join('\n');

  return `# GENERATED by scripts/fetch-content.mjs from events.legacy_slugs.
# Do not edit: the next build overwrites it. To change a redirect, change the
# content -- see data/backfill-legacy-slugs.sql.
#
# Order matters; first match wins. All rules here are 301s to a currently
# published event, and an event that is not published contributes none: a
# withdrawn event's legacy URL 404s rather than redirecting to the agenda.
# Recorded as acceptable at this scale rather than as correct.
#
# Both the encoded and the raw spelling are listed because Cloudflare's docs do
# not say whether matching happens on the encoded or the decoded path, and both
# forms reach this file from a real browser. Trailing-slash variants too, since
# Astro builds directories and either form resolves.
#
# Measured on the live asset router: the encoded WITH-slash source is 1 hop, as
# intended. The encoded WITHOUT-slash source is still 2, and no destination
# spelling can fix it -- the router normalises the trailing slash BEFORE
# _redirects is consulted, so /...casita redirects to /...casita/ first and only
# then matches. The no-slash sources therefore never fire. They are kept because
# they cost nothing and would matter if html_handling ever changed; changing
# html_handling to avoid one hop on a legacy URL is not a trade worth making.

${body}
`;
}
